node {

  stage('Checkout') {
    git credentialsId: 'github-lsd-members',
        url: 'git@github.com:jSherz/lsd-members.git'
  }

  ansiColor('gnome-terminal') {
    dir('frontend') {
      stage('Install') {
        sh 'yarn install'
      }

      stage('Lint') {
        sh 'yarn run lint'
      }

      stage('Test') {
        sh 'yarn run test -- --browsers HeadlessChrome --watch false --progress false'
      }
    }
  }

}
