node {

  stage('Checkout') {
    git credentialsId: 'github-lsd-members',
        url: 'git@github.com:jSherz/lsd-members.git'
  }

  ansiColor('gnome-terminal') {
    dir('frontend') {
      stage('Install') {
        sh 'yarn install'
      }

      stage('Lint') {
        sh 'yarn run lint'
      }

      stage('Test') {
        sh 'yarn run test-ci'

        withCredentials([string(credentialsId: 'lsd-members-coveralls', variable: 'COVERALLS_REPO_TOKEN')]) {
          sh 'COVERALLS_SERVICE_NAME=jenkins yarn run coveralls'
        }
      }
    }
  }

}
