language: node_js
dist: bionic
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
install:
  - cd frontend
  - npm install
script:
  - npm run test -- --progress=false --watch=false --browsers=ChromeHeadlessNoSandbox
  - npm run build-prod
