node {

  stage('Build') {
    sh 'sh deploy/prepare-build.sh'
  }

  withCredentials([
    string(credentialsId: 'lsd-prod-aws-id', variable: 'AWS_ACCESS_KEY_ID'),
    string(credentialsId: 'lsd-prod-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY')
  ]) {
    stage('Deploy to S3') {
      sh 'aws s3 cp -r dist/* s3://lsd-prod-frontend/'
    }

    stage('Invalidate cache') {
      sh 'aws configure set preview.cloudfront true'
      sh 'aws cloudfront create-invalidation ' +
        '--distribution-id E1LNJUAVS7YL91 ' +
        '--paths "index.html"'
    }
  }

}
