#!/usr/bin/env groovy

node {

  stage('Checkout') {
    git credentialsId: 'github-lsd-members',
        url: 'git@github.com:jSherz/lsd-members.git'
  }

  dir('backend') {
    stage('Setup DB') {
      withCredentials([
        file(credentialsId: 'lsd-dev-deploy', variable: 'DEPLOY_KEY'),
        string(credentialsId: 'lsd-dev-jwt-secret', variable: 'JWT_SECRET')
      ]) {
        sh 'chmod 0600 $DEPLOY_KEY'
        sh 'scp -i $DEPLOY_KEY src/it/resources/setup-e2e-db.sql deploy@api.dev.leedsskydivers.com:/home/api/scripts'
        sh 'ssh -i $DEPLOY_KEY deploy@api.dev.leedsskydivers.com \'sudo -H /usr/bin/python /opt/setup-e2e-db.py\''
      }
    }
  }

  dir('frontend') {
    stage('Install') {
      sh 'yarn install'
    }

    stage('e2e') {
      withCredentials([
        string(credentialsId: 'fb-test-user-pass', variable: 'FB_TEST_USER_PASS')
      ]) {
        ansiColor('css') {
          sh 'yarn run e2e-ci'
        }
      }
    }
  }

}
